---
# tasks file for ansible-coreos-autofs
- name: Create autofs config dir
  sudo: yes
  sudo_user: root
  file: path={{coreos_autofs_etc}} state=directory mode=0755

- name: Create install dir
  sudo: yes
  sudo_user: root
  file: path={{coreos_autofs_install_dir}} state=directory mode=0755

- name: Install autofs
  shell: >
    creates={{coreos_autofs_systemd}}/autofs.service
    docker run -v {{coreos_autofs_install_dir}}:/opt
    -v {{coreos_autofs_etc}}:/etc/autofs
    -v {{coreos_autofs_systemd}}:/etc/systemd/system
    -v /etc/default:/etc/default
    {{coreos_autofs_container}}

- name: Start autofs
  sudo: yes
  sudo_user: root
  service: name=autofs.service state=started enabled=yes
